### ISSUE TITLE
Attributes are not processed or applied on callables

### ISSUE THREAD

**Issue by BitPuffin** [boo-lang/boo#119]
Like the title said.

``` boo
[noatuhsauthaouhoaneunouhnau]
callable foo() as void
```

Compiles just fine.

More context and examples on the [mailing list](https://groups.google.com/forum/#!topic/boolang/X68xxrr2OdM)

But basically BindAndApplyAttributes does not override OnCallableDefinition so it doesn't process it at all.
Cheers

**Comment by masonwheeler** [comment]
Merged into master
