### ISSUE TITLE
http://boo.codehaus.org/ requires login

### ISSUE THREAD

**Issue by beruic** [boo-lang/boo#122]
I am unable to read the information there, because i have no idea of how to log in, and I can't see why I even should.

**Comment by masonwheeler** [comment]
Codehaus is dead now, and any links to it are obsolete.  They need to be removed.

**Comment by amigrave** [comment]
Boo definitely deserves a 1.0 and a home.

I guess a static collaborative website in `bamboo/boo#gh-pages` might be a good option if Rodrigo (@bamboo) agrees. A custom domain name could even be bound to it.

**Comment by masonwheeler** [comment]
The community has already set up a new site for the language, with a custom domain, over at http://boo-lang.org/.  It's still under development, but it's better than nothing...

**Comment by amigrave** [comment]
This is the first time I see this website :-)
I didn't even know there was a Boo2JS compiler !
Is the website registered in google crawler ? It doesn't appear in the first page when searching [`boo lang`](https://www.google.com/#q=boo+lang)

Does Rodrigo endorses this community website ?
If true, why do we still find so much boo.codehaus.org around this repository ? Even the description of the repo points to codehaus

**Comment by masonwheeler** [comment]
@amigrave We haven't heard anything from @bamboo on the subject.  Unfortunately he's been MIA for the last several months.  There's currently [an active discussion going on](https://groups.google.com/forum/#!topic/boolang/iqRauhAPLGw) on the official Boo discussion group regarding what we should do about it.  Feel free to drop in and offer any thoughts, if you'd like.

**Comment by amigrave** [comment]
@masonwheeler Thanks. Will do for sure !

**Comment by masonwheeler** [comment]
With Rodrigo back and development moved to boo-lang, this can be closed.
