### ISSUE TITLE
Boo lexer for CudaText

### ISSUE THREAD

**Issue by Alexey-T** [boo-lang/boo#124]
lexer for CudaText and Synwrite (2 editors use one lexer):
Now in addon-manager:
in Synwrite: Options/ AddonManager/ Install, in list type "boo" and choose Boo lexer. After installed, open any .boo file.
in Cudatext: same

lexer supports Tree panel.

**Comment by Alexey-T** [comment]
![boo](https://cloud.githubusercontent.com/assets/4154978/11915344/502cb8a2-a6b3-11e5-8505-da846fcb5725.png)

**Comment by masonwheeler** [comment]
Closing, as this appears to be an advertisement (albeit for something legitimately Boo-related) rather than a report of a Boo language issue.
