### ISSUE TITLE
PATCH - All Wiki links made internal and fixed, updated Home.md.

### ISSUE THREAD

**Issue by gnat** [boo-lang/boo#130]
Since we cannot submit Pull Requests to the Wiki, here's a patch that can be applied to the repository for someone with push access to: https://github.com/boo-lang/boo.wiki.git

[gnat_wiki_update.patch.zip](https://github.com/boo-lang/boo/files/96698/gnat_wiki_update.patch.zip)

You can apply this patch using: git apply gnat_wiki_update.patch

Thanks!

**Comment by bamboo** [comment]
Hi Nathaniel,

Thanks for the contribution!

I've added you to the Contributors team so you should now be able to apply the patch yourself and edit the wiki directly. Let me know if for some reason it doesn't work.

**Comment by gnat** [comment]
Thank you Rodrigo! The Wiki has been updated with the patch.

I'm training up new hires to use Boo, so we will be able to catch issues such as broken links and fix them as we use the documentation.

**Comment by masonwheeler** [comment]
Great work, thanks! :)
