### ISSUE TITLE
Incorrect Warning private constructor never used

### ISSUE THREAD

**Issue by BitPuffin** [boo-lang/boo#143]
With my current compiler version (some head from some point), compiling the following code spits out this warning:

``` WARNING: Private constructor 'Test.constructor' is never used.```

Here's the code:

``` boo
class Test:
	private def constructor():
		print "hey"

	def constructor(msg as string):
		self()
		print msg
```

If you run the code however it is evident that it is being used.

Not a terribly huge problem since it doesn't break anything but annoying nonetheless

**Comment by BitPuffin** [comment]
Actually, the call to the private constructor is not even necessary for it to run.

**Comment by BitPuffin** [comment]
A simple solution to this then would be to not warn if the private constructor doesn't take any parameters. But it's probably worth checking if this warning happens for private constructors with parameters as well even when they get used.

**Comment by masonwheeler** [comment]
I've seen this before; just never really considered it a high priority.  But if someone else is running into it, I'll take a look later on...

**Comment by masonwheeler** [comment]
Turns out that the visitor that checks whether private members are used was only checking `ReferenceExpression` types (ie. member names,) and not the `self` and `super` keywords that are used for invoking constructors.

**Comment by masonwheeler** [comment]
Well this is annoying.  My Git client seems to be on the fritz.  Twice now I've tried to push this change to GitHub, and twice it's appeared to work, but then the actual commit vanished into the aether. :(

I'll look at this further this evening, after work.

**Comment by masonwheeler** [comment]
Ugh.  The client was explicitly set to check this in to boo-lang/master, but it checked it in to my master instead.  [Have I ever mentioned how much I hate DVCSs, because they screw up like this all the time?](http://tech.turbu-rpg.com/657/i-am-officially-sick-of-dvcs)

Anyhoo, this is fixed in boo-lang/master now.

**Comment by BitPuffin** [comment]
Yeah I've been meaning to make a simple centralized scm.

**Comment by masonwheeler** [comment]
Actually, the git screwup appears to have gone deeper than that.  Somehow it seems to have replaced boo-lang/master with a copy of masonwheeler/master.  I'm currently investigating.  Please be careful if you check out before I manage to fix this; there's incomplete WIP code in there that may or may not work for you... :(

**Comment by masonwheeler** [comment]
There, I managed to get it all worked out. *Now* it should be safe to check out.

**Comment by BitPuffin** [comment]
Cool, thanks for looking into it!

On 22 April 2016 13:50:59 BST, masonwheeler <notifications@github.com> wrote:
>There, I managed to get it all worked out. *Now* it should be safe to
>check out.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/boo-lang/boo/issues/143#issuecomment-213415107

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
