### ISSUE TITLE
[Question] Embedding Boo

### ISSUE THREAD

**Issue by 0xFireball** [boo-lang/boo#144]
I rediscovered Boo today. Does Boo provide an API for embedding it with other ,NET applications? For example, compiling on the fly, or an embeddable scripting API like IronPython?

**Comment by popcatalin81** [comment]
This is a more complete example of using embedding Boo and using it as a DSL https://github.com/ayende/rhino-dsl

**Comment by masonwheeler** [comment]
Short answer: Yes; look at the `Boo.Lang.Interpreter` assembly, and `booish.exe` in particular as an example.

Long answer: Feel free to discuss questions about how to use Boo over on [our community forum](https://groups.google.com/forum/#!forum/boolang).  We can tell you all about using `Boo.Lang.Interpreter`, in as much detail as you need.  But this issues list is really for posting bug reports and feature requests.

Closing this to keep the issues list clean. :)
