### ISSUE TITLE
RuntimeServices.ToBool Does not handle Value Types properly

### ISSUE THREAD

**Issue by BitPuffin** [boo-lang/boo#148]
Hello!

So, I have some code which looks roughly like this:

``` boo
def Rofl(o):
  if o:
    print o.ToString()

```

Since ```o``` is an ```object```, it makes sense to null check it. And it works just fine when you pass anything that derives from ```object```, and a few of the primitive types like ```int```.

However, a user-defined struct will not work on code like this.
Here's a repl session that demonstrates this:

``` boo
>>> import Boo.Lang.Runtime
>>> struct Lol:
...     a as int
...
>>> def Rofl(o):
...     if o:
...         print o.ToString()
...
>>> Rofl(object())
System.Object
>>> Rofl(Lol())
System.InvalidCastException: Unable to cast object of type 'Lol' to type 'System.IConvertible'.
   at Boo.Lang.Runtime.RuntimeServices.CheckNumericPromotion(Object value)
   at Boo.Lang.Runtime.RuntimeServices.UnboxBoolean(Object value)
   at Boo.Lang.Runtime.RuntimeServices.UnboxBooleanDispatcher(Object value, Object[] arguments)
   at Boo.Lang.Runtime.RuntimeServices.ToBool(Object value)
   at Input4Module.Rofl(Object o) in C:\Users\usefulProgrammer\input4:line 2
   at Input6Module.Main(String[] argv) in C:\Users\usefulProgrammer\input6:line 1
>>> RuntimeServices.ToBool(object())
true
>>> RuntimeServices.ToBool(Lol())
System.InvalidCastException: Unable to cast object of type 'Lol' to type 'System.IConvertible'.
   at Boo.Lang.Runtime.RuntimeServices.CheckNumericPromotion(Object value)
   at Boo.Lang.Runtime.RuntimeServices.UnboxBoolean(Object value)
   at Boo.Lang.Runtime.RuntimeServices.UnboxBooleanDispatcher(Object value, Object[] arguments)
   at Boo.Lang.Runtime.RuntimeServices.ToBool(Object value)
   at Input8Module.Main(String[] argv) in C:\Users\usefulProgrammer\input8:line 1
```

At least this is the case on my version, I'm not on latest (yet).

**Comment by Pangamini** [comment]
Well AFAIK, expression such as this this performs casting of the value to
bool, not comparision with null. It is just that types declare an implicit
cast operator to bool that returns the 'obj==null' value. So either you add
this implicit cast operator to your type, or write the exact expression 'if
o == null' instead

**Comment by masonwheeler** [comment]
@Pangamini Agreed, though the error message could be handled better.  It reports a problem converting `Lol` to `IConvertible`, when the actual problem is with converting `Lol` to `bool`.

**Comment by BitPuffin** [comment]
Yeah comparing it to null helps indeed. However shouldn't value types always be considered truthy regardless?

I consider it a flaw in the language at least.

**Comment by masonwheeler** [comment]
>However shouldn't value types always be considered truthy regardless?

"Truthiness" is for dynamically-typed languages that don't have a proper concept of `bool` as its own, distinct type.  TBH I consider any implicit conversion to bool in a statically-typed language such as Boo (or C# for that matter) to be a flaw in the language.

**Comment by Pangamini** [comment]
bool 'false' is a value type. So are nullables.

**Comment by BitPuffin** [comment]
I'm not so sure. I think I've heard the term truthy used for lots of strongly (and not) typed dynamic languages that have a specific boolean type. Such as Ruby.

Then it usually just refers to what is to be considered true in a conditional expression.

What you say about only bool being valid in an if has merit though. Problem is that boo does not work like that. So I think all value types should be considered true for consistency I guess. Though I wonder if numbers are all true or simply 0 is false. Will have to check later I guess.

**Comment by masonwheeler** [comment]
@BitPuffin Going off the example you posted, `Rofl(0)` prints nothing, while `Rofl(1)` prints `1`.

**Comment by BitPuffin** [comment]
Ah right, figured I might be wrong about that.

Either way, then I guess we should statically not compile code that contains something of type ```object``` in a boolean context, unless ducky is turned on. That seems like the best semantics to me.

**Comment by masonwheeler** [comment]
Just checked in a change that will give a more useful error message.

Defining an `op_Implicit` conversion to `bool` on your struct also works.

**Comment by masonwheeler** [comment]
Also, if what you really want to do is null-check a parameter passed in to a function, why not simply use the `[Required]` attribute?

**Comment by BitPuffin** [comment]
Because it was a null check with an else. Otherwise I almost always use ```[required]```.
