### ISSUE TITLE
Clicking on the main banner on the website links to a broken page

### ISSUE THREAD

**Issue by santagada** [boo-lang/boo#171]
On the website if you click on the main banner you end up in: http://boo-lang.org/Main.aspx?TAB=VBB4Arduino

which is broken.

**Comment by masonwheeler** [comment]
Thanks, but this repo is only for the Boo codebase.  Issues for boo-lang.org should be reported at https://github.com/boo-language/boo-language.github.io/issues

Would you mind reposting these over there?
