### ISSUE TITLE
Online converter link is broken on Getting Started

### ISSUE THREAD

**Issue by santagada** [boo-lang/boo#172]
http://boo-lang.org/Main.aspx?TAB=Getting%20Started

if you click on the online converter it points to: http://codeconverter.sharpdevelop.net/SnippetConverter.aspx which is broken.

**Comment by masonwheeler** [comment]
Thanks, but this repo is only for the Boo codebase.  Issues for boo-lang.org should be reported at https://github.com/boo-language/boo-language.github.io/issues

Would you mind reposting these over there?
