### ISSUE TITLE
How do you open a file in boo?

### ISSUE THREAD

**Issue by sayRequil** [boo-lang/boo#178]
I wish to make a web framework for Boo, and I am wondering if there is some way to open a file in Boo?

Thanks.

**Comment by masonwheeler** [comment]
You would do it the same way you open a file anywhere else in the .NET framework.  Depending on what you want to do with it, there are several options.  Have a look at the [System.IO.File](https://msdn.microsoft.com/en-us/library/system.io.file(v=vs.110).aspx) class for various options.

Also, if you're specifically looking at the idea of a Boo Web framework, have a look at [Web.Boo](https://github.com/masonwheeler/Web.Boo).
