### ISSUE TITLE
Setting icon at compile time ?

### ISSUE THREAD

**Issue by Guevara-chan** [boo-lang/boo#180]
So far I was forced to use ResHacker cmdline interface,  yet it's pretty much suboptimal.
Is there any way to add winicon though compiler ?

**Comment by masonwheeler** [comment]
I just checked, and it doesn't appear that there's any support for project icons in the Boo compiler.  I'll look into adding it.

**Comment by Guevara-chan** [comment]
...So ? I still need it to simplify building process.

**Comment by masonwheeler** [comment]
Sorry, things have been busy lately with Thanksgiving and all.  I'll probably get this added over the weekend.

**Comment by masonwheeler** [comment]
Wow, that took longer than I thought.  It should be working now, as of the latest commit.

Added a value to the compiler context: `Context.Parameters.Icon`, and new command-line flag: `i:<icon file name>`, which will set `Context.Parameters.Icon`.  If this is set, and the file is a valid filename referring to a valid `.ico` file, the compiler will build that icon into the generated assembly.
