### ISSUE TITLE
Native Boo.Lang.dll embedding ?

### ISSUE THREAD

**Issue by Guevara-chan** [boo-lang/boo#187]
Recently I found myself noticing, that `ILMerge`, while being quite a nice tool, is not widely spread among .net developers. Naturally, additional dependencies is far from desirable for open-source projects, especially  mad with unconventional already programming languages.

Is there any way to make runtime lib embeddable from compiler options with all required tools being already present in Boo distro ?

**Comment by popcatalin81** [comment]
You can do this with a post-build invocation for ILMerge.  You can invoke it manually or use a msbuild task like this one: https://www.nuget.org/packages/MSBuild.ILMerge.Task/ if you prefer. 

I don't think adding an option to boo compiler is feasible, as the amount of work this feature requires is non-trivial and ILMerge is superseded for .Net core by CoreRT, see: https://github.com/dotnet/corert/tree/master/samples/WebApi

**Comment by Guevara-chan** [comment]
> You can do this with a post-build invocation for ILMerge. 
Unfortunately - yes, you can. It's called 'extra dependency' and makes project rebuilding harder for other users, so I advice you to refrain from such things when developing open-sourced projects.

>ILMerge is superseded for .Net core by CoreRT
I guess 4.0 will be our best target for, like, next 5 years.

**Comment by masonwheeler** [comment]
Sorry, but @popcatalin81 is right.  This isn't something that belongs in the Boo compiler.  Adding it would basically involve re-implementing most of ILMerge within Boo.Lang.Compiler.
