### ISSUE TITLE
Interpolated string extension methods

### ISSUE THREAD

**Issue by Guevara-chan** [boo-lang/boo#190]
Consider following sample:
```
import System.Runtime.CompilerServices
[Extension] def cap(text as string):
	print Char.ToUpper(text[0]) + text[1:].ToLower()
name = "tester"
"hello, $name !".cap()
```
Do you expect it to work ? Me too. However, compiler disagree:
>BCE0043: Unexpected token: \<EOL\>.
>BCE0043: Unexpected token: .

What could be done ? Is it bug or somewhat intended restriction ?

**Comment by masonwheeler** [comment]
This should work.  You're seeing a parser error, which happens well before any interpretation of string interpolations, and one that doesn't reproduce on my end, so I'm not quite sure what's going on with your code.

**Comment by Guevara-chan** [comment]
Cool. That being said, enclosing interpolated string with brackets works for some reason:
`("hello, $name !").cap()`

**Comment by masonwheeler** [comment]
Right.  If it's a simple reference expression, no parens or brackets are needed.  They're only needed if you're enclosing more than one identifier, like `$(name.ToUpper)`, so the parser knows how much is interpolation and how much is the literal string.

**Comment by Guevara-chan** [comment]
Um, cool... I guess. So, this was intended behavior ?

**Comment by masonwheeler** [comment]
Yeah.  Did you ever figure out what was going on with the parse error?
