### ISSUE TITLE
How can i ref to value when calling function from DllImport

### ISSUE THREAD

**Issue by Rabios** [boo-lang/boo#212]
Hi devs!

I have problem with using pointers from library...
Anyway... I did bindings for library but pointers doesn't work well i think so...

```boo
// Define the camera to look into our 3d world
camera as Camera3D
camera.position = Vector3(10.0f, 10.0f, 10.0f)  // Camera position
camera.target = Vector3(0.0f, 0.0f, 0.0f)       // Camera looking at point
camera.up = Vector3(0.0f, 0.0f, 0.0f)           // Camera up vector (rotation towards target)
camera.fovy = 45.0f                             // Camera field-of-view Y
camera.type = CameraType.CAMERA_PERSPECTIVE     // Camera mode type
cubePosition = Vector3(0.0f, 2.0f, 0.0f)
cubeSize = Vector3(2.0f, 2.0f, 2.0f)
```

```boo
c = do(ref c as Camera3D):
	UpdateCamera(c)
c(camera)
```

So i think it doesn't work properly, Here is definition from DllImport:

```boo
// Update camera position for selected mode
[DllImport("raylib", CallingConvention: CallingConvention.Cdecl)]
def UpdateCamera(ref camera as Camera3D):
	pass
```

idk why it doesn't work as intended, Sorry but i did not found right docs about pointers...

How can i use ref with DllImport for function uses pointers? Sorry i know this shouldn't be here...
Any code example would be welcome...

**Comment by masonwheeler** [comment]
You say "it doesn't work."  How so?  What do you expect it to do and what it it doing instead?

Can you share the definitions of `Camera3D`, from both the Boo side and the C side, to verify that they match?  Do you have access to the code?  It looks like you're using [raylib](https://github.com/raysan5/raylib), so can you build it from source and trace into it with mixed-mode debugging to see how the camera's properties match up with what you're seeing on the managed side?

**Comment by Rabios** [comment]
@masonwheeler Sure!
Here is bindings repo, It's working but problem persists in using pointers somehow...

Here is the `Camera3D` from Boo side...
https://github.com/Rabios/raylib-boo/blob/master/raylib_boo.boo#L367

Here is the `Camera3D` from C side...
https://github.com/raysan5/raylib/blob/master/src/raylib.h#L288

But see this example, I'm porting it to Boo...
https://github.com/raysan5/raylib/blob/master/examples/core/core_3d_picking.c

Problem in line 48 of the example, idk how to call it correctly...

**Comment by Rabios** [comment]
About what it does, It should show a cube in 3D world space can be pickable with mouse...
See here: https://www.raylib.com/examples/web/core/loader.html?name=core_3d_picking

But instead, It does not shows 3D world, Only text and when i click everywhere it sets collision to true, idk why this happen...

**Comment by masonwheeler** [comment]
One thing I notice right away is that `fovy` is defined as `float` in the original code but `int` in your translation.  Floats can represent int values, but their binary representation is very different, so it's likely that you're ending up with a camera with a bizarrely wrong field of view that's not focusing properly on your 3D scene.

Again, have you tried using the debugger in mixed mode to trace into the call and verify that the camera's data values come out the same on the native side as what you set on the managed side?  If not, this would indicate a problem with either the data typing or the alignment.

**Comment by Rabios** [comment]
Thanks!
And no...I'm using shared lib of raylib, So you need me to debug via print values right?

**Comment by Rabios** [comment]
![Screenshot (173)](https://user-images.githubusercontent.com/47897019/99570254-57591f80-29da-11eb-8dc3-7c8f6ef7ffee.png)

I tried to edit and change fovy to single as you said, But it does not...

**Comment by masonwheeler** [comment]
Yeah, use print values to debug if you can't get in with the debugger.  Try and verify if what's coming through on the native side is the same as what you're feeding into it on the managed side.

**Comment by Rabios** [comment]
Info:

Camera position: 10, 10, 10 (x, y, z)
Camera target: 0, 0, 0 (x, y, z)
Camera up: 0, 0, 0 (x, y, z)
Camera fovy: 45

idk if this can help

**Comment by Rabios** [comment]
Look, I changed camera position to 0, 1, 0
But i get weird behaviour...

Camera position: 0, 1, 4.371139E-08
Camera target: 0, 0, 0
Camera up: 0, 0, 0
Camera fovy: 45

**Comment by masonwheeler** [comment]
That's very odd.  The data looks right, at first, but it's definitely getting corrupted in some way when you change it.

How are you changing it?  Just changing the code that sets the initial values and re-running it, or adding code to modify it later?

**Comment by Rabios** [comment]
Changing from code, After loop it should be as i set it...

**Comment by masonwheeler** [comment]
Is it possible that something on the native side is adjusting the camera's position slightly in response to something?  `(8.742278E-08, 0.9999999, 0.9999999)` is *extremely* close to `(0, 1, 1)`.

**Comment by Rabios** [comment]
Maybe?

But what's with the x?

**Comment by Rabios** [comment]
OK, really i don't know what should i do with this, And dll working right with my Lua bindings...
https://github.com/Rabios/raylua

Do you think it's bug by Boo compiler?

**Comment by masonwheeler** [comment]
It's hard to tell from this, whether it's a bug in the compiler, or if it's something weird going on on the native side.

**Comment by Rabios** [comment]
OK, Is using pointer when i made issue correct?

How to call with ref?

**Comment by masonwheeler** [comment]
I think what you're doing should work.  There are a handful of common mistakes when doing stuff like this, but aside from the `fovy` error, I'm not seeing any of them in your camera code.  The "wrong" numbers look like they're only off by a tiny amount, so it could easily be a precision/rounding issue, the type of thing that pops up in floating point code all the time.

In the spirit of always asking the obvious questions and verifying assumptions, have you made sure that the C equivalent of this same code works as expected?

**Comment by Rabios** [comment]
Yes, It works!
But Boo one doesn't, I think it's problem with Boo...

**Comment by masonwheeler** [comment]
Well, you're setting up the camera correctly, and it's displaying text correctly, but the 3D part isn't rendering.  Seems to me the most likely culprit is a bad call in the 3D code somewhere.

**Comment by Rabios** [comment]
OH MY GOD!
![Screenshot (174)](https://user-images.githubusercontent.com/47897019/99580679-69da5580-29e8-11eb-86e9-11a5b7a91441.png)

Then it's problem in dimensions...

**Comment by Rabios** [comment]
Solved, Thanks and will close issue!

**Comment by masonwheeler** [comment]
Glad to see you got it working.  What was the problem?

**Comment by Rabios** [comment]
Problem was that i used values from Raylib-cs port, Which is not compatible with C one (And i don't know how this can happen...)
Sorry, I was dump...

Here is screenshot of victory!
![Screenshot (175)](https://user-images.githubusercontent.com/47897019/99582408-be7ed000-29ea-11eb-8320-bfc58b0c126f.png)
[Source Code](https://github.com/Rabios/raylib-boo/blob/master/core_3d_picking.boo)

**Comment by masonwheeler** [comment]
Congratulations on getting it working!
